#overlap //12
LEARNING_RATE : 5e-5
BATCH_SIZE : 64
NUM_WORKERS : 32
PATIENCE : 5
IMAGE_SIZE : 256
PRETRAINED: False
TRAIN_LOSS: ["L1","Perceptual"]
TRAIN_WEIGHTS_LOSS: [0.2, 0.8]
VAL_LOSS: ["Perceptual", "MSE"]
VAL_WEIGHTS_LOSS: [0.2, 0.8]
AUGMENT: Medium
VAL_PLOT_PER_EPOCH: 3
TEST_PLOT_PER_EPOCH: 6
PLOT_IMAGES: False
OUTPUT_RANGE: [0,1] #check output of sigmoid
split: [0.8,0.2,0.2]
DDP: False






datasets: &DATASET_OPTIONS
  - &BRAZILPretrain BRAZILPretrain
  - &BRAZILFinetune BRAZILFinetune

paths: &PATH_OPTIONS
  # - &MOEI_PATH /home/santosh/Projects/geo_physics/meixia_noise_removal/MoEI_airborne_magdata/data/AirMag_Mag_lag_cut.csv""/home/santosh/Projects/geo_physics/meixia_noise_removal/MAG_Lev_final_tr1_cut.csv
  # - &MOEI_PATH /home/santosh/Projects/geo_physics/meixia_noise_removal/MoEI_airborne_magdata/data/MAG_LEV_DGRF_surveyline_tie_100m_cut.csv""/home/santosh/Projects/geo_physics/meixia_noise_removal/MoEI_airborne_magdata/data/MAG_LEV_DGRF_surveyline_tie_100m_cut.csv
  - &BRAZIL_PATH_v2 ["/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1101.npy", 
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1102.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1103.npy",

                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1104.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1106.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1107.npy",

                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1108.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1067.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1113.npy",

                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1127.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1121.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1131.npy",

                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1109.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1120.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1071.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1126.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train1_1129.npy",


                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train2_1067.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train2_1126.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train2_1127_v2.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train2_1127.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/train2_1101.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/val1_1113.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/val1_1127.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/val1_1129.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/val2_1129.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/val1_1101.npy",

                    # "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/test1_1111.npy",
                    "/home/santosh/Projects/geo_physics/meixia_noise_removal/brazil_v2_data/arrays/airmag_recent.npy"]


TASK: Denoising
MODEL: UNet
LEARNING_SCHEDULER : CosineAnnealingLR
NUM_EPOCHS : 30
STRIDE: 32
DROP_LAST: True
CUDA_DEVICE: 0
NUM_CLASSES: 1
DATASET: *BRAZILFinetune
PATH: *BRAZIL_PATH_v2
LOAD_DIR: "/home/santosh/Projects/geo_physics/JOURNAL_RUNS/pretraining/final_brazil_runs/varying_dataset_size/finetuning_w_pretraining/17_datasets/2025-03-21_13-30-42/best_checkpoint.pth"
# "/home/santosh/Projects/geo_physics/meixia_noise_removal/pretraining/final_brazil_runs/finetuning_256_5e5_l1loss_maintain_same_patch_also/2024-12-10_10-11-14"
#"/home/santosh/Projects/geo_physics/meixia_noise_removal/MoEI_airborne_magdata/final_brazil_runs/512_patches/2024-09-27_10-11-06"
SAVE_DIR: airmag_20022025
RECONSTRUCT_OPTION: 'entire'
CREATE_CSV: True